version: '3'
services:
  front:
    build: .
    ports:
     - "3000:3000"

  mariadb:
    image: "mariadb"
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: connekt
      MYSQL_DATABASE: connekt
    volumes:
      - mariadbvolume:/var/lib/mysql/data

volumes:
  mariadbvolume:
